### ISSUE TITLE
Hits/collisions sometimes don't register

### ISSUE THREAD

**Issue by ngokevin** [feiss/supersays#1]
Perhaps try https://github.com/ngokevin/kframe/tree/master/components/aabb-collider

**Comment by feiss** [comment]
Yeah I'm aware of this. I think sometimes it's because of the speed of the controller and sometimes it's because the rounded shape of the simon area. I'll fix it, thanks!

**Comment by feiss** [comment]
fixed on 983b56af730bd4de51004528a8269c04b38328e9
